 # # ======================================
 # Programmer: Anthony Llena
 # Date Programmed: April 03, 2026
 # Time Programmed: 11:24 AM
 #
 # Objectives:
 #   This script implements a rule-based classification model using Decision Tree
 #   for the processed healthcare stroke dataset. It trains the model using the
 #   prepared dataset splits, evaluates performance on test and unseen data, and
 #   generates rule-based outputs for interpretation.
 #
 # Key Tasks Performed:
 #   1. Load the processed training, testing, and unseen datasets
 #   2. Train a Decision Tree classifier using the stroke target variable
 #   3. Evaluate the model using accuracy, precision, recall, F1-score, specificity, and ROC-AUC
 #   4. Save confusion matrices, tree visualization, feature importances, and extracted rules
 # # ======================================

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree


# ======================================
# Path and File Configuration
# ======================================
# Resolve project directories once so every file read/write operation
# uses consistent absolute paths regardless of the current working directory.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR = BASE_DIR / "outputs" / "decision_tree"

# ======================================
# Input Data Loading
# ======================================
# The project already provides official train, test, and unseen splits.
# This script reuses those files directly to stay aligned with the project pipeline.
X_train = pd.read_csv(DATA_DIR / "X_train.csv")
X_test = pd.read_csv(DATA_DIR / "X_test.csv")
X_unseen = pd.read_csv(DATA_DIR / "X_unseen.csv")

y_train = pd.read_csv(DATA_DIR / "y_train.csv").values.ravel()
y_test = pd.read_csv(DATA_DIR / "y_test.csv").values.ravel()
y_unseen = pd.read_csv(DATA_DIR / "y_unseen.csv").values.ravel()

MODEL_NAME = "decision_tree"
MAX_DEPTH = 4
RANDOM_STATE = 42

# Output files generated by this script.
METRICS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_metrics.csv"
IMPORTANCE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_feature_importance.csv"
RULES_PATH = OUTPUT_DIR / f"{MODEL_NAME}_rules.txt"
TREE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_tree.png"
CM_TEST_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test.png"
CM_UNSEEN_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen.png"
CM_TEST_TABLE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test.csv"
CM_UNSEEN_TABLE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen.csv"
CM_TEST_LABELS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test_labels.csv"
CM_UNSEEN_LABELS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen_labels.csv"
REPORT_TEST_PATH = OUTPUT_DIR / f"{MODEL_NAME}_classification_report_test.csv"
REPORT_UNSEEN_PATH = OUTPUT_DIR / f"{MODEL_NAME}_classification_report_unseen.csv"


def ensure_output_dir() -> None:
    """Create the output directory before saving reports and figures."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def build_model() -> DecisionTreeClassifier:
    """
    Create the Decision Tree classifier used for the rule-based model.

    The tree is intentionally constrained to keep the generated rules readable
    for reporting and discussion in the paper.
    """
    return DecisionTreeClassifier(
        criterion="gini",
        max_depth=MAX_DEPTH,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=RANDOM_STATE,
    )


def compute_metrics(y_true, y_pred, y_proba) -> dict[str, float]:
    """
    Compute the core evaluation metrics required by the project.

    Specificity is derived manually from the confusion matrix because it is not
    returned directly by scikit-learn's standard classification report.
    """
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1_score": f1_score(y_true, y_pred, zero_division=0),
        "specificity": tn / (tn + fp) if (tn + fp) else 0.0,
        "roc_auc": roc_auc_score(y_true, y_proba),
    }


def build_classification_report_table(y_true, y_pred) -> pd.DataFrame:
    """Convert the sklearn classification report into a structured table."""
    report_df = pd.DataFrame(
        classification_report(y_true, y_pred, zero_division=0, output_dict=True)
    ).transpose()
    report_df.index.name = "label"
    return report_df.reset_index().round(4)


def build_confusion_matrix_tables(cm) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build two confusion matrix tables:
    1. a standard labeled matrix
    2. a compact TN/FP/FN/TP summary
    """
    tn, fp, fn, tp = cm.ravel()

    matrix_df = pd.DataFrame(
        cm,
        index=["Actual No Stroke", "Actual Stroke"],
        columns=["Predicted No Stroke", "Predicted Stroke"],
    )

    labels_df = pd.DataFrame(
        [
            {"label": "TN", "value": tn},
            {"label": "FP", "value": fp},
            {"label": "FN", "value": fn},
            {"label": "TP", "value": tp},
        ]
    )

    return matrix_df, labels_df


def save_confusion_matrix(cm, title: str, output_path: Path) -> None:
    """Render and save a confusion matrix figure for the requested dataset split."""
    plt.figure(figsize=(7, 5))
    plt.imshow(cm, interpolation="nearest", cmap=plt.cm.Blues)
    plt.colorbar()
    tick_marks = [0, 1]
    labels = ["No Stroke", "Stroke"]
    plt.xticks(tick_marks, labels)
    plt.yticks(tick_marks, labels)
    for row_idx in range(cm.shape[0]):
        for col_idx in range(cm.shape[1]):
            plt.text(col_idx, row_idx, cm[row_idx, col_idx], ha="center", va="center", color="black")
    plt.title(title)
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()


def save_tree_visualization(model: DecisionTreeClassifier) -> None:
    """Export a readable visualization of the trained Decision Tree."""
    plt.figure(figsize=(22, 12))
    plot_tree(
        model,
        feature_names=X_train.columns,
        class_names=["No Stroke", "Stroke"],
        filled=True,
        rounded=True,
        fontsize=8,
    )
    plt.title(f"Decision Tree (max_depth={MAX_DEPTH})")
    plt.tight_layout()
    plt.savefig(TREE_PATH, dpi=300, bbox_inches="tight")
    plt.close()


def save_feature_importance(model: DecisionTreeClassifier) -> pd.DataFrame:
    """
    Save feature importance scores to support interpretation of the model.

    The resulting table is sorted from the most influential predictor to the least.
    """
    importance_df = (
        pd.DataFrame(
            {
                "feature": X_train.columns,
                "importance": model.feature_importances_,
            }
        )
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )
    importance_df["importance"] = importance_df["importance"].round(4)
    importance_df.to_csv(IMPORTANCE_PATH, index=False)
    return importance_df


def save_rules(model: DecisionTreeClassifier) -> str:
    """Extract the tree's decision rules as plain text and save them to disk."""
    rules = export_text(model, feature_names=list(X_train.columns))
    with open(RULES_PATH, "w", encoding="utf-8") as file:
        file.write(rules)
    return rules


def evaluate_split(model: DecisionTreeClassifier, X_data: pd.DataFrame, y_data, split_name: str):
    """
    Evaluate the trained model on a specific dataset split.

    This keeps test and unseen validation consistent by using the same metrics,
    report format, and confusion matrix generation process.
    """
    y_pred = model.predict(X_data)
    y_proba = model.predict_proba(X_data)[:, 1]
    metrics = compute_metrics(y_data, y_pred, y_proba)
    cm = confusion_matrix(y_data, y_pred)
    report_df = build_classification_report_table(y_data, y_pred)
    matrix_df, labels_df = build_confusion_matrix_tables(cm)

    output_path = CM_TEST_PATH if split_name == "Test" else CM_UNSEEN_PATH
    cm_table_path = CM_TEST_TABLE_PATH if split_name == "Test" else CM_UNSEEN_TABLE_PATH
    cm_labels_path = CM_TEST_LABELS_PATH if split_name == "Test" else CM_UNSEEN_LABELS_PATH
    report_path = REPORT_TEST_PATH if split_name == "Test" else REPORT_UNSEEN_PATH

    save_confusion_matrix(cm, f"Decision Tree Confusion Matrix ({split_name})", output_path)
    matrix_df.to_csv(cm_table_path)
    labels_df.to_csv(cm_labels_path, index=False)
    report_df.to_csv(report_path, index=False)

    return metrics, report_df, matrix_df, labels_df


def save_metrics_table(test_metrics: dict[str, float], unseen_metrics: dict[str, float]) -> pd.DataFrame:
    """Save the core evaluation metrics as a single clean CSV summary table."""
    metrics_df = pd.DataFrame(
        [
            {"dataset_split": "test", **test_metrics},
            {"dataset_split": "unseen", **unseen_metrics},
        ]
    ).round(4)
    metrics_df.to_csv(METRICS_PATH, index=False)
    return metrics_df


def main() -> None:
    """
    Run the complete Decision Tree workflow from training to artifact export.

    Sequence:
    1. Ensure the output directory exists
    2. Build and train the Decision Tree model
    3. Save model interpretation artifacts
    4. Evaluate on both test and unseen datasets
    5. Save structured evaluation outputs as CSV tables
    """
    ensure_output_dir()

    # Train the rule-based classifier using the predefined project split.
    model = build_model()
    model.fit(X_train, y_train)

    # Save interpretation artifacts before reporting metrics.
    importance_df = save_feature_importance(model)
    rules = save_rules(model)
    save_tree_visualization(model)

    # Evaluate the model on the held-out test set and the unseen validation set.
    test_metrics, test_report_df, test_cm_df, test_cm_labels_df = evaluate_split(model, X_test, y_test, "Test")
    unseen_metrics, unseen_report_df, unseen_cm_df, unseen_cm_labels_df = evaluate_split(model, X_unseen, y_unseen, "Unseen")

    # Persist all summary metrics in a clean tabular format.
    metrics_df = save_metrics_table(test_metrics, unseen_metrics)

    print("\nDecision Tree Metrics")
    print(metrics_df.to_string(index=False))

    print("\nDecision Tree Test Classification Report")
    print(test_report_df.to_string(index=False))

    print("\nDecision Tree Unseen Classification Report")
    print(unseen_report_df.to_string(index=False))

    print("\nDecision Tree Test Confusion Matrix")
    print(test_cm_df.to_string())
    print(test_cm_labels_df.to_string(index=False))

    print("\nDecision Tree Unseen Confusion Matrix")
    print(unseen_cm_df.to_string())
    print(unseen_cm_labels_df.to_string(index=False))

    print(f"\nMetrics table saved to: {METRICS_PATH}")
    print(f"Feature importances saved to: {IMPORTANCE_PATH}")
    print(f"Rules saved to: {RULES_PATH}")
    print(f"Tree plot saved to: {TREE_PATH}")
    print(f"Test confusion matrix saved to: {CM_TEST_PATH}")
    print(f"Unseen confusion matrix saved to: {CM_UNSEEN_PATH}")
    print(f"Test confusion matrix table saved to: {CM_TEST_TABLE_PATH}")
    print(f"Unseen confusion matrix table saved to: {CM_UNSEEN_TABLE_PATH}")
    print(f"Test confusion matrix labels saved to: {CM_TEST_LABELS_PATH}")
    print(f"Unseen confusion matrix labels saved to: {CM_UNSEEN_LABELS_PATH}")
    print(f"Test classification report table saved to: {REPORT_TEST_PATH}")
    print(f"Unseen classification report table saved to: {REPORT_UNSEEN_PATH}")


if __name__ == "__main__":
    main()
