# # ======================================
# Programmer: Anthony Llena
# Date Programmed: April 03, 2026
# Time Programmed: 12:03 PM
#
# Objectives:
#   This script implements a Random Forest classification model for the
#   processed healthcare stroke dataset. It trains the model using the
#   prepared dataset splits, evaluates performance on test and unseen data,
#   and generates structured outputs for reporting and comparison.
#
# Key Tasks Performed:
#   1. Load the processed training, testing, and unseen datasets
#   2. Train a Random Forest classifier using the stroke target variable
#   3. Evaluate the model using accuracy, precision, recall, F1-score, specificity, and ROC-AUC
#   4. Save confusion matrices, feature importances, and classification report tables
# # ======================================

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import StratifiedKFold, cross_validate


# ======================================
# Path and File Configuration
# ======================================
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR = BASE_DIR / "outputs" / "random_forest"

# ======================================
# Input Data Loading
# ======================================
X_train = pd.read_csv(DATA_DIR / "X_train.csv")
X_test = pd.read_csv(DATA_DIR / "X_test.csv")
X_unseen = pd.read_csv(DATA_DIR / "X_unseen.csv")

y_train = pd.read_csv(DATA_DIR / "y_train.csv").values.ravel()
y_test = pd.read_csv(DATA_DIR / "y_test.csv").values.ravel()
y_unseen = pd.read_csv(DATA_DIR / "y_unseen.csv").values.ravel()

MODEL_NAME = "random_forest"
RANDOM_STATE = 42
N_ESTIMATORS = 300
MAX_DEPTH = 8

# Output files generated by this script.
METRICS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_metrics.csv"
IMPORTANCE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_feature_importance.csv"
CM_TEST_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test.png"
CM_UNSEEN_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen.png"
CM_TEST_TABLE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test.csv"
CM_UNSEEN_TABLE_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen.csv"
CM_TEST_LABELS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_test_labels.csv"
CM_UNSEEN_LABELS_PATH = OUTPUT_DIR / f"{MODEL_NAME}_confusion_matrix_unseen_labels.csv"
REPORT_TEST_PATH = OUTPUT_DIR / f"{MODEL_NAME}_classification_report_test.csv"
REPORT_UNSEEN_PATH = OUTPUT_DIR / f"{MODEL_NAME}_classification_report_unseen.csv"


def ensure_output_dir() -> None:
    """Create the output directory before saving reports and figures."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def build_model() -> RandomForestClassifier:
    """
    Create the Random Forest classifier used as the chosen algorithm.

    The configuration favors stable results and class balancing while keeping
    the model straightforward to explain in the paper.
    """
    return RandomForestClassifier(
        n_estimators=N_ESTIMATORS,
        max_depth=MAX_DEPTH,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )


def compute_metrics(y_true, y_pred, y_proba) -> dict[str, float]:
    """
    Compute the evaluation metrics required by the project brief.

    Specificity is calculated manually from the confusion matrix.
    """
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision": precision_score(y_true, y_pred, zero_division=0),
        "recall": recall_score(y_true, y_pred, zero_division=0),
        "f1_score": f1_score(y_true, y_pred, zero_division=0),
        "specificity": tn / (tn + fp) if (tn + fp) else 0.0,
        "roc_auc": roc_auc_score(y_true, y_proba),
    }


def specificity_cv_score(estimator, X_data, y_data) -> float:
    """Compute specificity for a fitted estimator during cross-validation."""
    y_pred = estimator.predict(X_data)
    cm = confusion_matrix(y_data, y_pred)
    tn, fp, _, _ = cm.ravel()
    return tn / (tn + fp) if (tn + fp) else 0.0


def run_cross_validation() -> dict[str, float]:
    """
    Perform 10-fold stratified cross-validation on the training split only.

    The averaged fold scores populate the Training (CV) column in the metrics table.
    """
    cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)
    scoring = {
        "accuracy": "accuracy",
        "precision": "precision",
        "recall": "recall",
        "f1_score": "f1",
        "specificity": specificity_cv_score,
        "roc_auc": "roc_auc",
    }

    cv_results = cross_validate(
        build_model(),
        X_train,
        y_train,
        cv=cv,
        scoring=scoring,
        n_jobs=-1,
    )

    return {
        "accuracy": cv_results["test_accuracy"].mean(),
        "precision": cv_results["test_precision"].mean(),
        "recall": cv_results["test_recall"].mean(),
        "f1_score": cv_results["test_f1_score"].mean(),
        "specificity": cv_results["test_specificity"].mean(),
        "roc_auc": cv_results["test_roc_auc"].mean(),
    }


def build_classification_report_table(y_true, y_pred) -> pd.DataFrame:
    """Convert the sklearn classification report into a structured table."""
    report_df = pd.DataFrame(
        classification_report(y_true, y_pred, zero_division=0, output_dict=True)
    ).transpose()
    report_df.index.name = "label"
    return report_df.reset_index().round(4)


def build_confusion_matrix_tables(cm) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build two confusion matrix tables:
    1. a standard labeled matrix
    2. a compact TN/FP/FN/TP summary
    """
    tn, fp, fn, tp = cm.ravel()

    matrix_df = pd.DataFrame(
        cm,
        index=["Actual No Stroke", "Actual Stroke"],
        columns=["Predicted No Stroke", "Predicted Stroke"],
    )

    labels_df = pd.DataFrame(
        [
            {"label": "TN", "value": tn},
            {"label": "FP", "value": fp},
            {"label": "FN", "value": fn},
            {"label": "TP", "value": tp},
        ]
    )

    return matrix_df, labels_df


def save_confusion_matrix(cm, title: str, output_path: Path) -> None:
    """Render and save a confusion matrix figure for the requested dataset split."""
    plt.figure(figsize=(7, 5))
    plt.imshow(cm, interpolation="nearest", cmap=plt.cm.Blues)
    plt.colorbar()
    tick_marks = [0, 1]
    labels = ["No Stroke", "Stroke"]
    plt.xticks(tick_marks, labels)
    plt.yticks(tick_marks, labels)
    for row_idx in range(cm.shape[0]):
        for col_idx in range(cm.shape[1]):
            plt.text(col_idx, row_idx, cm[row_idx, col_idx], ha="center", va="center", color="black")
    plt.title(title)
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()


def save_feature_importance(model: RandomForestClassifier) -> pd.DataFrame:
    """
    Save feature importance scores to support interpretation of the model.

    The resulting table is sorted from the most influential predictor to the least.
    """
    importance_df = (
        pd.DataFrame(
            {
                "feature": X_train.columns,
                "importance": model.feature_importances_,
            }
        )
        .sort_values("importance", ascending=False)
        .reset_index(drop=True)
    )
    importance_df["importance"] = importance_df["importance"].round(4)
    importance_df.to_csv(IMPORTANCE_PATH, index=False)
    return importance_df


def evaluate_split(model: RandomForestClassifier, X_data: pd.DataFrame, y_data, split_name: str):
    """
    Evaluate the trained model on a specific dataset split.

    This keeps test and unseen validation consistent by using the same metrics,
    report format, and confusion matrix generation process.
    """
    y_pred = model.predict(X_data)
    y_proba = model.predict_proba(X_data)[:, 1]
    metrics = compute_metrics(y_data, y_pred, y_proba)
    cm = confusion_matrix(y_data, y_pred)
    report_df = build_classification_report_table(y_data, y_pred)
    matrix_df, labels_df = build_confusion_matrix_tables(cm)

    output_path = CM_TEST_PATH if split_name == "Test" else CM_UNSEEN_PATH
    cm_table_path = CM_TEST_TABLE_PATH if split_name == "Test" else CM_UNSEEN_TABLE_PATH
    cm_labels_path = CM_TEST_LABELS_PATH if split_name == "Test" else CM_UNSEEN_LABELS_PATH
    report_path = REPORT_TEST_PATH if split_name == "Test" else REPORT_UNSEEN_PATH

    save_confusion_matrix(cm, f"Random Forest Confusion Matrix ({split_name})", output_path)
    matrix_df.to_csv(cm_table_path)
    labels_df.to_csv(cm_labels_path, index=False)
    report_df.to_csv(report_path, index=False)

    return metrics, report_df, matrix_df, labels_df


def save_metrics_table(
    cv_metrics: dict[str, float], test_metrics: dict[str, float], unseen_metrics: dict[str, float]
) -> pd.DataFrame:
    """Save the core evaluation metrics in the manuscript-ready table layout."""
    metric_order = ["accuracy", "precision", "recall", "f1_score", "specificity", "roc_auc"]
    metric_labels = {
        "accuracy": "Accuracy",
        "precision": "Precision",
        "recall": "Recall",
        "f1_score": "F1-score",
        "specificity": "Specificity",
        "roc_auc": "ROC-AUC",
    }

    metrics_df = pd.DataFrame(
        {
            "Metric": [metric_labels[metric] for metric in metric_order],
            "Training (CV)": [round(cv_metrics[metric], 4) for metric in metric_order],
            "Test Set": [round(test_metrics[metric], 4) for metric in metric_order],
            "Unseen Set": [round(unseen_metrics[metric], 4) for metric in metric_order],
        }
    )
    metrics_df.to_csv(METRICS_PATH, index=False)
    return metrics_df


def main() -> None:
    """
    Run the complete Random Forest workflow from training to artifact export.

    Sequence:
    1. Ensure the output directory exists
    2. Build and train the Random Forest model
    3. Save feature importance artifacts
    4. Evaluate on both test and unseen datasets
    5. Save structured evaluation outputs as CSV tables
    """
    ensure_output_dir()

    model = build_model()
    model.fit(X_train, y_train)

    cv_metrics = run_cross_validation()
    save_feature_importance(model)

    test_metrics, test_report_df, test_cm_df, test_cm_labels_df = evaluate_split(model, X_test, y_test, "Test")
    unseen_metrics, unseen_report_df, unseen_cm_df, unseen_cm_labels_df = evaluate_split(
        model, X_unseen, y_unseen, "Unseen"
    )

    metrics_df = save_metrics_table(cv_metrics, test_metrics, unseen_metrics)

    print("\nRandom Forest Metrics")
    print(metrics_df.to_string(index=False))

    print("\nRandom Forest Test Classification Report")
    print(test_report_df.to_string(index=False))

    print("\nRandom Forest Unseen Classification Report")
    print(unseen_report_df.to_string(index=False))

    print("\nRandom Forest Test Confusion Matrix")
    print(test_cm_df.to_string())
    print(test_cm_labels_df.to_string(index=False))

    print("\nRandom Forest Unseen Confusion Matrix")
    print(unseen_cm_df.to_string())
    print(unseen_cm_labels_df.to_string(index=False))

    print(f"\nMetrics table saved to: {METRICS_PATH}")
    print(f"Feature importances saved to: {IMPORTANCE_PATH}")
    print(f"Test confusion matrix saved to: {CM_TEST_PATH}")
    print(f"Unseen confusion matrix saved to: {CM_UNSEEN_PATH}")
    print(f"Test confusion matrix table saved to: {CM_TEST_TABLE_PATH}")
    print(f"Unseen confusion matrix table saved to: {CM_UNSEEN_TABLE_PATH}")
    print(f"Test confusion matrix labels saved to: {CM_TEST_LABELS_PATH}")
    print(f"Unseen confusion matrix labels saved to: {CM_UNSEEN_LABELS_PATH}")
    print(f"Test classification report table saved to: {REPORT_TEST_PATH}")
    print(f"Unseen classification report table saved to: {REPORT_UNSEEN_PATH}")


if __name__ == "__main__":
    main()
